In [ ]:
import numpy as np

# **Array**

In [ ]:
#Reverse Iteration
arr0 = np.array((1, 2, 3, 4, 5))

def reverse_iteration(arr):
  for i in range(len(arr)-1,-1,-1): #starting from index 4 and ending at index 0 because -1 given as stop
    print(arr[i])

reverse_iteration(arr0)

5
4
3
2
1


In [ ]:
#Copy Array
arr0 = np.array((1, 2, 3, 4, 5))

def copy(arr):
  new_arr = np.array([0]*len(arr))
  for i in range(len(arr)):
    new_arr[i] = arr[i]
  return new_arr

arr1 = copy(arr0)
print(arr1)

[1 2 3 4 5]


In [ ]:
#Resize Array
arr0 = np.array((1, 2, 3, 4, 5))

def resize(arr, new_size):
  new_arr = np.array([0]*new_size)
  for i in range(len(arr)):
    new_arr[i] = arr[i]
  return new_arr

arr1 = resize(arr0, 7)
print(arr1)

[1 2 3 4 5 0 0]


In [ ]:
#Reverse Out of Place
arr0 = np.array((1, 2, 3, 4, 5))

def reverse_out(arr):
  new_arr = np.array([0]*len(arr))
  for i in range(len(arr)):
    new_arr[i] = arr[len(arr)-i-1]
  return new_arr

arr1 = reverse_out(arr0)
print(arr1)

[5 4 3 2 1]


In [ ]:
#Reverse In Place (Efficient)
arr0 = np.array((1, 2, 3, 4, 5, 6))

def reverse_in(arr):
  i = 0
  j = len(arr) - 1
  while i < j:
    arr[i], arr[j] = arr[j], arr[i] #Last iteration occurs with i equal to j
    i += 1                          #Means the middle is reached.
    j -= 1
  return arr

arr1 = reverse_in(arr0)
print(arr1)

[6 5 4 3 2 1]


In [ ]:
#Shift Left
arr0 = np.array((1, 2, 3, 4, 5, 6))

def shiftLeft(arr):
  for i in range(1, len(arr)):
    arr[i-1] = arr[i]
  arr[len(arr)-1] = 0
  print(arr)

shiftLeft(arr0)

[2 3 4 5 6 0]


In [ ]:
#Shift Right
arr0 = np.array((1, 2, 3, 4, 5, 6))

def shiftRight(arr):
  for i in range(1, len(arr)):
    arr[-i] = arr[-(i+1)]
  arr[0] = 0
  print(arr)

shiftRight(arr0)

[0 1 2 3 4 5]


In [ ]:
#Rotate Left
arr0 = np.array((1, 2, 3, 4, 5, 6))

def rotateLeft(arr):
  tmp = arr[0]
  for i in range(1, len(arr)):
    arr[i-1] = arr[i]
  arr[len(arr)-1] = tmp
  print(arr)

rotateLeft(arr0)

[2 3 4 5 6 1]


In [ ]:
#Rotate Right
arr0 = np.array((1, 2, 3, 4, 5, 6))

def rotateRight(arr):
  tmp = arr[len(arr)-1]
  for i in range(1, len(arr)):
    arr[-i] = arr[-(i+1)]
  arr[0] = tmp
  print(arr)

rotateRight(arr0)

[6 1 2 3 4 5]


In [ ]:
#Insert
arr0 = np.array((1, 2, 3, 4, 5, 6))

def insert(arr, value, ind):
  new_arr = np.array([0]*(len(arr)+1))
  for i in range(0, len(arr)):
    # if i == ind:
    #   # new_arr[ind] = value
    #   # new_arr[i+1] = arr[i]
    #   new_arr[i] = 0
    #   continue
    # else:
      new_arr[i] = arr[i]
  for i in range(1, ind+1):
      new_arr[-i] = new_arr[-(i+1)]
  #arr[len(arr)-1] = 0
  # for i in range(ind+1, len(new_arr)):
  #   new_arr[i] = arr[i]
  print(new_arr)

insert(arr0, 5, 2)

[1 2 3 4 5 5 6]


In [ ]:
def summation(arr):
   sums = np.zeros(1,3)
   for i in arr:

In [ ]:
# Rotate Matrix
seats = np.array([['A', 'B', 'C', 'D', 'E'],
                  ['F', 'G', 'H', 'I', 'J'],
                  ['K', 'L', 'M', 'N', 'O'],
                  ['P', 'Q', 'R', 'S', 'T'],
                  ['U', 'V', 'W', 'X', 'Y'],
                  ['Z', 'AA', 'BB', 'CC', 'DD']], dtype=str)

def rotateLeft(arr):
  M, N = arr.shape
  for m in range(M):
    temp = arr[m][0]
    for n in range(1,N):
      arr[m][n-1] = arr[m][n]
    arr[m][n] = temp
  print(arr)

rotateLeft(seats)

[['B' 'C' 'D' 'E' 'A']
 ['G' 'H' 'I' 'J' 'F']
 ['L' 'M' 'N' 'O' 'K']
 ['Q' 'R' 'S' 'T' 'P']
 ['V' 'W' 'X' 'Y' 'U']
 ['AA' 'BB' 'CC' 'DD' 'Z']]


# **Linked List**

## Singly Linked

In [ ]:
# Initialization
class Node:
  def __init__(self, elem, next = None):
    self.elem = elem
    self.next = next

In [ ]:
# Creation from Array
def createList(arr):
    head = Node(arr[0])
    tail = head                     #We use this to create a 'copy' to the LL which we'll be working on
    for i in range(1, len(arr)):    #If we use head instead, then the actual
      tail.next = Node(arr[i])      #starting point or 'head' of the LL
      tail = tail.next              #moves along with it.
    return head

building_1 = createList(np.array(['Red', 'Green', 'Yellow', 'Blue']))

In [ ]:
# Iteration
def iteration(head):
  temp = head
  while temp != None:
    print(temp.elem)
    temp = temp.next
iteration(building_1)

Red
Green
Yellow
Blue


In [ ]:
# Get Node
def nodeAt(head, ind):
  temp = head
  count = 0
  while ind > count and temp!=None:
    temp = temp.next
    count += 1
  if temp == None:
    print("Invalid Index")
  else:
    return temp

nodeAt(building_1, 1)

In [ ]:
# Insert Element (Iterative)
building_1 = createList(np.array(['Red', 'Green', 'Yellow', 'Blue']))
def insert(head, elem, ind):
  cur = head
  prev = None
  count = 0
  while cur != None:
    if ind == count:
      if count == 0:
        head = Node(elem, head)
      else:
        prev.next = Node(elem, cur)
    if ind == count + 1 and cur.next == None:
      cur.next = Node(elem, None)
      break
    prev = cur
    cur = cur.next
    count += 1
  return head

A = insert(building_1, 'Gu', 4)
iteration(A)

Red
Green
Yellow
Blue
Gu


In [ ]:
# Insert Element (In place)
building_1 = createList(np.array(['Red', 'Green', 'Yellow', 'Blue']))
def counter(head):
  count = 0
  temp = head
  while temp != None:
    temp = temp.next
    count += 1
  return count

def insertAt(head, elem, ind):
  temp = head
  length = counter(temp)
  if ind == 0:
    head = Node(elem, head)
  elif ind == length:
    cur = nodeAt(head, length - 1)
    cur.next = Node(elem, None)
  else:
    prev = nodeAt(head, ind - 1)
    cur = nodeAt(head, ind)
    prev.next = Node(elem, cur)
  iteration(head)
  print()
  return head

insertAt(building_1, "Gu", 0)
iteration(building_1)

Gu
Red
Green
Yellow
Blue

Red
Green
Yellow
Blue


In [ ]:
# Reversing Linked List
building_1 = createList(np.array(['Red', 'Green', 'Yellow', 'Blue']))
def reverse(head):
  newHead = None
  temp = head
  while temp != None:
    after = temp.next     # Saves ref of temp.next before | n = temp = [Red], temp.next = [Green]
    temp.next = newHead   # we assign the next value to new head | temp.next = [Green] -> [None]
    newHead = temp        # and then change the ref of new head to temp | newHead = [Red], so temp.next = [None] -> [Red]
    temp = after          # temp = [Red] -> [Green]
  return newHead
B = reverse(building_1)
iteration(B)

Blue
Yellow
Green
Red


In [ ]:
# Rotate Left
building_1 = createList(np.array(['Red', 'Green', 'Yellow', 'Blue']))
def rotateLeft(head):
  temp = head
  newHead = head.next
  while temp.next != None:
    temp = temp.next
  temp.next = head
  head.next = None
  return newHead

B = rotateLeft(building_1)
iteration(B)

Green
Yellow
Blue
Red


In [ ]:
# Dummy Headed Linear
building_1 = createList(np.array(['Red', 'Green', 'Yellow', 'Blue']))
def createDHList(arr):
  dh = Node(None)
  temp = dh
  for i in range(len(arr)):
    temp.next = Node(arr[i])
    temp = temp.next
  return dh

A = createDHList(np.array(['Red', 'Green', 'Yellow', 'Blue']))
iteration(A)

None
Red
Green
Yellow
Blue


In [ ]:
# Insert Element in a Sorted Linked List

def sorted_insert(head, elem):
  temp = head
  prev = None
  nod = Node(elem)
  while temp is not None:
    if head.elem >= elem:
      n = head
      head = nod
      nod.next = n
      break
    if temp.next is not None:
      if temp.next.elem >= elem:
        n = temp.next
        temp.next = nod
        nod.next = n
        break
    else:
      temp.next = nod
      break
    prev = temp
    temp = temp.next
  print()
  return head
A = createList(np.array([1, 3, 5, 7, 8, 11]))
B = sorted_insert(A, 33)
iteration(B)


1
3
5
7
8
11
33


In [ ]:
# Sort a Linked List that is already Sorted on Absolute Values
def sort(head):
  temp = head

A = createList(np.array([7, 2, 15, 5, 8, 11]))
B = sorted_insert(A, 33)
iteration(B)


7
2
15
5
8
11
33


In [ ]:
# Finding the Middle Element of a Linked List (By Traversal)
def leng(head):
  temp = head
  length = 0
  while temp is not None:
    temp = temp.next
    length += 1
  return length

def midElem(head):
  length = leng(head)
  temp = head
  count = 0
  while count < length//2:
    if length%2 == 0:
      if count == length//2 - 1:
        return (temp.elem + temp.next.elem)/2
    temp = temp.next
    count += 1
  return temp.elem

A = createList(np.array([7, 2, 15, 5, 8, 11, 13, 2]))
B = midElem(A)
print(B)

6.5


In [ ]:
# Finding the Middle Element of a Linked List (By Pointers)
def midElemPointer(head):
  temp = head


A = createList(np.array([7, 2, 15, 5, 8, 11, 13, 2]))
B = midElem(A)
print(B)

6.5


In [ ]:
# Detecting Loops or Cycle in a Linked List (Marking Nodes) [Using Array]
def detectLoop(head):
  length = leng(head)
  arr0 = np.array([0]*length)
  temp = head
  count = 0
  while head is not None:
    if head in arr0:
      return True
    arr0[count] = head
    head = head.next
  return False

In [ ]:
# Detecting Loops or Cycle in a Linked List (Marking Nodes) [Using Member of Node]
def detectLoop(head):


In [ ]:
# Remove Odd Numbers from Linked List
def removeOdd(head):
  temp = head
  prev = None
  while temp != None:
    if not temp.elem%2 == 0:
      if temp is head:
        head = head.next

      prev.next = temp.next
    else:
      prev = temp
    temp = temp.next
  return head

A = createList(np.array([3, 15, 5, 8, 11, 13, 2, 5]))
B = removeOdd(A)
iteration(B)

AttributeError: 'NoneType' object has no attribute 'next'

In [ ]:
def IsSumPossible(head, n):
  temp = head
  while temp is not None:
    cur = temp.next
    while cur is not None:
      if (cur.elem+temp.elem) == n:
        return True
      cur = cur.next
    temp = temp.next

A = createList([1, 2, 3, 4, 5])
IsSumPossible(A, 5)

True

In [ ]:
def remove_Duplicates(head):
  temp = head
  while temp is not None:
    cur = temp.next
    prev = temp
    while cur is not None:
      if cur.elem != temp.elem:
        prev = cur
      else:
        prev.next = cur.next
      cur = cur.next
    temp = temp.next
  return head
A = createList([101, 101, 103, 101, 102, 103, 104, 105, 105])
B = remove_Duplicates(A)
iteration(B)

101
103
102
104
105


In [ ]:
def reverse(head):
  newHead = None
  temp = head
  before = None
  after = temp.next
  while temp is not None:
    after = temp.next
    temp.next = before
    before = temp
    temp = after
  newHead = before
  return newHead

105
104
103
102
101


In [ ]:
def reverse(head):
  temp = head
  while temp is not None:
    n = temp.next
    prev = temp
    prev.next = temp.next
    temp = n
A = createList([101, 102, 103, 104, 105])
B = reverse(A)
iteration(B)

### Doubly Linked

In [ ]:
#Initialization
class DoublyNode:
  def __init__(self, elem, next = None, prev = None):
    self.elem = elem
    self.next = next
    self.prev = prev

In [ ]:
#Creation
def createList(arr):
  dh = DoublyNode(None, None, None)
  dh.next = dh
  dh.prev = dh
  temp = dh
  for i in range(len(arr)):
    nod = DoublyNode(arr[i], dh, temp)
    temp.next = nod
    temp = temp.next
    dh.prev = temp
  return dh

A = createList(np.array(['Red', 'Green']))
iteration(A)

Red
Green


In [ ]:
# Iteration
def iteration(dh):
  temp = dh.next
  while temp != dh:
    print(temp.elem)
    temp = temp.next

A = createList(np.array(['Red', 'Green', 'Yellow', 'Blue']))
iteration(A)

Red
Green
Yellow
Blue


In [ ]:
# Get Node
A = createList(np.array(['Red', 'Green', 'Yellow', 'Blue']))
def nodeAt(dh, ind):
  temp = dh.next
  count = 0
  while count < ind and temp != dh:
    if ind == count + 1 and temp.next is dh:

      temp = temp.next
    count += 1
  if ind != count or temp == dh:
    return None
  else:
    return temp

nodeAt(A, 0)

In [ ]:
# A = createList(np.array(['Red', 'Green', 'Yellow', 'Blue']))
# def nodeAt(dh, ind):
#   temp = dh.next
#   count = 0
#   while temp != dh:
#     if ind == count:
#       return temp
#     temp = temp.next
#     count += 1
#   return 1

# nodeAt(A, 0)

In [ ]:
# Insertion
def insert(dh, elem, ind):
  temp = dh.next
  count = 0
  while temp != dh:
    # print(temp.elem)
    if ind == count:
      # print(temp.prev, temp, temp.next)
      nod = DoublyNode(elem, temp, temp.prev)
      # print(nod.prev, nod.next)
    print(temp.elem)
    temp = temp.next
    count += 1
  return dh

A = createList(np.array(['Red', 'Green', 'Yellow', 'Blue']))
B = insert(A, 'Gu', 1)
iteration(B)

Red
Green
Yellow
Blue
Red
Green
Yellow
Blue


In [ ]:
# Insertion
def insertAt(dh, elem, ind):
  cur = nodeAt(dh, ind)
  prev = cur.prev
  nod = DoublyNode(elem, None, None)
  prev.next = nod
  nod.next = cur
  return dh

A = createList(np.array(['Red', 'Green', 'Yellow', 'Blue']))
B = insertAt(A, 'Gu', 0)
iteration(B)

Gu
Red
Green
Yellow
Blue


In [ ]:
# Doubly Linked Circular
def dh_circular(arr):
  dh = DoublyNode(None, None, None)
  dh.next = dh
  dh.prev = dh
  temp = dh
  for i in range(len(arr)):
    nod = DoublyNode(arr[i], dh, temp)
    temp.next = nod
    temp = temp.next
    dh.prev = temp
  return dh

def iteration(dh):
  temp = dh.next
  while temp != dh:
    print(temp.elem)
    temp = temp.next

A = dh_circular(np.array(['Red', 'Green', 'Yellow', 'Blue']))
iteration(A)

Red
Green
Yellow
Blue


In [ ]:
def reverse_circular(dh):
  # temp = dh.next
  # while temp is not dh:
  #   node = temp
  #   temp = temp.next
  #   prev = node.prev
  #   node.prev = node.next
  #   node.next = prev

  # head_next = dh.next
  # dh.next = dh.prev
  # dh.prev = head_next

  # return dh
  temp = dh.next
  while temp is not dh:
    nod = temp
    temp = temp.next
    prev = nod.prev
    nod.prev = nod.next
    nod.next = prev
  head_next = dh.next
  dh.next = dh.prev
  dh.prev = head_next
  return dh
A = dh_circular(np.array(['Red', 'Green', 'Yellow', 'Blue']))
B = reverse_circular(A)
iteration(B)

Blue
Yellow
Green
Red


# **Stack**

In [ ]:
# Initialization
class Node:
  def __init__(self, elem, next = None):
    self.elem = elem
    self.next = next

class Stack:
  def __init__(self):
    self.top = None

  def push(self, elem):
    prev = self.top
    self.top = Node(elem, prev)

  def pop(self):
    e = self.top
    if self.top is None:
      return None
    self.top = self.top.next
    return e.elem

  def peek(self):
    if self.top is None:
      return None
    else:
      return (self.top.elem)

  def isEmpty(self):
    temp = self.top
    c = 0
    while temp != None:
      temp = temp.next
      c += 1
    if c > 0:
      return False
    else:
      return True

def print_stack(st):
  if st.isEmpty():
    return
  p = st.pop()
  print('|',p,end=' ')
  print('|')
  # if p<10:
  #   print(' |')
  # else:
  #   print('|')
  #print('------')
  print_stack(st)
  st.push(p)

st = Stack()
st.push(4)
st.push(3)
st.push(5)
st.push(1)
st.push(9)
print_stack(st)
print('Peeked Element: ',st.peek())
print('Popped Element: ',st.pop())
print('Popped Element: ',st.pop())
print('Popped Element: ',st.pop())
print('Peeked Element: ',st.peek())
print_stack(st)
print('Popped Element: ',st.pop())
print('Popped Element: ',st.pop())
print_stack(st)
print('Peeked Element: ',st.peek())
print('Popped Element: ',st.pop())
print(st.isEmpty())

| 9 |
| 1 |
| 5 |
| 3 |
| 4 |
Peeked Element:  9
Popped Element:  9
Popped Element:  1
Popped Element:  5
Peeked Element:  3
| 3 |
| 4 |
Popped Element:  3
Popped Element:  4
Peeked Element:  None
Popped Element:  None
True


In [ ]:
import numpy as np
temperatures = [99,73,74,75,71,69,72,76,71]
def dailyTemperatures(temps):
  stack = []
  output = temps
  for i in range(len(temps)-1):
    while len(stack) != 0:
      if output[stack[-1]] < temps[i+1]:
        x = stack.pop()
        output[x] = (i+1) - x
      else:
        break

    if temps[i] < temps[i+1]:
      output[i] = 1
    else:
      stack += [i]
  temps[len(temps)-1] = 0

  while len(stack) != 0:
    output[stack.pop()] = 0

  return output

print(dailyTemperatures(temperatures))

[0, 1, 1, 4, 2, 1, 1, 0, 0]


In [ ]:
def dailyTemperatures(arr):
  countStack = Stack()
  for x in range (len(arr)-1):
    while not countStack.isEmpty():
      if arr[countStack.peek()] < arr[x+1]:
        temp = countStack.pop()
        arr[temp] = x - temp + 1
      else:
        break
    if arr[x] < arr[x+1]:
      arr[x] = 1
    else:
      countStack.push(x)
    arr[len(arr)-1] = 0
    print(arr[x], countStack.peek())

  print(countStack.peek())
  while not countStack.isEmpty():
    arr[countStack.pop()] = 0
  return arr

temperatures = [99, 73,74,75,71,69,68,76,73]
dailyTemperatures(temperatures)

99 0
1 0
1 0
75 3
71 4
69 5
1 0
76 7
7


[0, 1, 1, 4, 3, 2, 1, 0, 0]

In [ ]:
def evalRPN(tokens):
  stack = []
  for i in tokens:
    stack += [i]
    if i == '/':
      stack.pop()
      b = stack.pop()
      a = stack.pop()
      stack += [int(a)/int(b)]
    elif i == '*':
      stack.pop()
      stack += [int(stack.pop())*int(stack.pop())]
    elif i == '+':
      stack.pop()
      stack += [int(stack.pop())+int(stack.pop())]
    elif i == '-':
      stack.pop()
      b = stack.pop()
      a = stack.pop()
      stack += [int(a)-int(b)]
    return stack.pop()
tokens = ["2","1","+","3","*"]
tokens = ["4","13","5","/","+"]
tokens = ["10","6","9","3","+","-11","*","/","*","17","+","5","+"]
evalRPN(tokens)

22

In [ ]:
def rotate_stack(stack, k):
  stack0 = Stack()
  stack1 = Stack()
  stack2 = Stack()
  c = 0
  temp = stack
  while not temp.isEmpty():
    temp.pop()
    c += 1
  k = k%c
  for i in range(k):
    stack2.push(stack.pop())
  stack0.push(stack.pop())
  while not stack2.isEmpty():
    stack0.push(stack2.pop())
  while not stack1.isEmpty():
    stack0.push(stack1.pop())

  return stack0

# **Hashing**

Implement a function remove(hashTable, key) that takes a key and a hash-table as
parameters. The function removes the key-value pair from the aforementioned hashtable if such a
key-value pair (whose key matches the key passed as argument) exists in the hashtable and return
the table. If the key does not exist, the function returns the same hash table.
Consider, Node class, hash_function and hashTable are given to you. You just need to complete
the remove(hashTable, key) function.
class Node:
def __init__(self, key, value, next=None):
self.key, self.value, self.next = key, value, next

Python Notation:
def remove(hashTable, key):

In [ ]:
def check(key):
    v = 0
    for i in key:
        if i.isnumeric():
            v += int(i)
        else:
            v += ord(i)
    return v % 3

def remove(hashTable, key):
    index = check(key)
    if hashTable[index] is not None:
        cur = hashTable[index]
        while cur is not None:
            prev = cur
            if cur.key == key:
                cur = cur.next
                prev.next = cur
                break
            cur = cur.next
    else:
        return hashTable
    return hashTable

# **Binary Tree**

### *Tree Node*


In [ ]:
# Tree Node
class BTNode:
  def __init__(self, elem, left = None, right = None):
    self.elem = elem
    self.left = left
    self.right = right

### *PreOrder*

In [ ]:
# Traverse Pre Order
def pre_order(root):
  if root is None:
    return
  print(root.elem, end = ' ')
  pre_order(root.left)
  pre_order(root.right)

### *InOrder*

In [ ]:
# Traverse Inorder
def inorder(root):
  if root is None:
    return
  inorder(root.left)
  print(root.elem, end=' ')
  inorder(root.right)

### *PostOrder*

In [ ]:
# Traverse Post Order
def post_order(root):
  if root is None:
    return
  post_order(root.left)
  post_order(root.right)
  print(root.elem, end = ' ')

### *Tree from Array*

In [ ]:
# Construction from Array
def tree_construction(arr, i = 1):
  if i >= len(arr) or arr[i] is None:
    return
  root = BTNode(arr[i])
  root.left = (tree_construction(arr, 2*i))
  root.right = (tree_construction(arr, 2*i + 1))
  return root

root2 = tree_construction([None, 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', None, None, None, 'I', 'J', None, 'K'])
inorder(root2)

H D B E A I F J C G K 

### *Count Nodes*

In [ ]:
# Count Nodes
def count(root):
    if root is None:
        return 0
    return 1 + count(root.left) + count(root.right)

### *Get Level/Depth of Node*

In [ ]:
# Get Level
def get_level(root, lvl, elem):
    if root is None:
        return 0
    if root.elem == elem:
        return lvl                          #Returns lvl of the elem when found
    L = get_level(root.left, lvl+1, elem)   #Checks left subtree and store value
    if L != 0:
        return L                            #If L != 0 i.e found in left subtree, return the value (L = lvl)
    L = get_level(root.right, lvl+1, elem)  #If reaches here, means not found in left subtree
    return L                                #So we search right subtree and return the lvl

### *Get Height of Node*

In [ ]:
# Height of Node
def height(root, i = 0):
    if root is None:
        return i
    L = height(root.left, i+1)
    R = height(root.right, i+1)
    if L > R:
        return L
    return R

### *Full BT Checker*

In [ ]:
# Check if the Tree is Full/Strict
def is_full(root):
  if root is None:
    return True
  if root.left is None and root.right is None:
    return True
  if root.left is not None and root.right is not None:
    return is_full(root.left) and is_full(root.right)
  return False

root = BTNode(10)
root.left = BTNode(5)
root.right = BTNode(15)
# Ensuring strict binary tree by manually adding 0 or 2 children to each node
root.left.left = BTNode(3)
root.left.right = BTNode(7)
# root.right.left = BTNode(13)
# root.right.right = BTNode(17)

print(is_full(root))

True


### *Degenerate BT Checker*

In [ ]:
# Check if the Tree is Degenerate
def is_degen(root):
  if root is None:
    return True
  if root.left is not None and root.right is not None:
    return False
  return (is_degen(root.left) and is_degen(root.right))

# Check if the Tree is Left Skewed
def is_leftSkew(root):
  if root is None:
    return True
  L = True
  if root.right is not None:
    return False
  if root.left is not None:
    return L and is_leftSkew(root.left)
  return L

root = BTNode(10)
root.left = BTNode(5)
# root.right.left = BTNode(13)  #False
root.left.left = BTNode(3)
root.left.left.left= BTNode(2)

print(is_degen(root))
print(is_leftSkew(root))

False
False


In [ ]:
root = BTNode(15)
n2 = BTNode(10)
n3 = BTNode(25)
n4 = BTNode(8)
n5 = BTNode(12)
n6 = BTNode(20)
n7 = BTNode(30)
n8 = BTNode(6)
n9 = BTNode(9)
n10 = BTNode(18)
n11 = BTNode(22)

root.left = n2
root.right = n3

n2.left = n4
n2.right = n5

n3.left = n6
n3.right = n7

n4.left = n8
n4.right = n9

n6.left = n10
n6.right = n11

pre_order(root)
print()
inorder(root)
print()
post_order(root)
print()
print(count(root))
print()
print(get_level(root, 0, 20))
print(height(root))

15 10 8 6 9 12 25 20 18 22 30 
6 8 9 10 12 15 18 20 22 25 30 
6 9 8 12 10 18 22 20 30 25 15 
11

2
4


In [ ]:
# Print BT in Ascending Order
def ascending(root):
  if root is None:
    return
  x = root.elem
  cur = root
  while cur is not None:
    if cur.elem < x:
      x = cur.elem
      cur = cur.left
    if cur.elem > x:
      cur = cur.right
    print(x)
  # return root

In [ ]:
#Driver Code
root=BTNode(71)
n2 = BTNode(27)
n3 = BTNode(62)
n4 = BTNode(80)
n5 = BTNode(75)
n6 = BTNode(41)
n7 = BTNode(3)
n8 = BTNode(87)
n9 = BTNode(56)
n10 = BTNode(19)
n11 = BTNode(89)

root.left = n2
root.right = n3

n2.left = n4
n2.right = n5

n3.left = n6
n3.right = n7

n4.left = n8
n4.right = n9

n7.left = n10
n7.right = n11

ascending(root)

## Previous Exam Questions

Given a Binary Tree, complete a function that finds if the given Binary Tree is a SumTree or not.
A SumTree is a Binary Tree where the value of a node is equal to the sum of the nodes present
in its left subtree and right subtree. An empty tree is SumTree and the sum of an empty tree can
be considered as 0. A leaf node is also considered as SumTree. The function should return True
if it is a SumTree and otherwise False.
Consider the Node class for Binary Tree already defined with elem, left and right variables. You
can use helper functions.
YOU CANNOT USE LIST OR DICTIONARY, any built-in function, or global variables.
Python Notation:
def sumTree(root):

In [ ]:
def summation(root):
    if root is None:
        return 0
    sum = summation(root.left) + summation(root.right)
    sum += root.elem
    return sum

def product(root):
  if root is None:
    return 1
  x = product(root.left) * product(root.right)
  x = x*root.elem
  return x

def sumTree(root):
    if root is None:
        return
    x = summation(root.left) + summation(root.right)
    if x != root.elem:
        return False
    sumTree(root.left)
    sumTree(root.right)
    return True

root = BTNode(26)
n2 = BTNode(10)
n3 = BTNode(3)
n4 = BTNode(6)
n5 = BTNode(4)
n6 = BTNode(3)

root.left = n2
root.right = n3

n2.left = n4
n3.left = n5

n3.right = n6

sumTree(root)
print(product(n2))

60


You are given a binary tree where each node stores a character. You are given the root of a
binary tree and a key as inputs. The key is valid if there is a path from the root to a leaf node in
the given tree. Now, your Task is to implement a recursive function named is_Valid(root, key)
that determines if the key is valid or not. The function should return True if the key is valid and
False otherwise.
Consider the Node class for Binary Tree already defined with elem, left and right variables. You
can use helper functions and extra parameters if required. You can not use any other data
structure than the binary tree.

In [ ]:
def is_Valid(root, key, i = 0):
  if root is None:
    return True
  if i < len(key) and root.elem == key[i]:
    if i == len(key)-1:
      if root.left != None or root.right != None:
        return False
    return is_Valid(root.left, key, i+1) or is_Valid(root.right, key, i+1)
  else:
    return False

root = tree_construction([None, 'C', 'S', 'R', 'T', 'E', 'M', 'P', None, None, None, None, None, None, 'D'])
inorder(root)
is_Valid(root, 'CRA')


T S E C M R D P 

False

# **Binary Search Tree**

### *Tree Node*

In [ ]:
class BTNode:
  def __init__(self, elem):
    self.elem = elem
    self.left = None
    self.right = None

### *InOrder*

In [ ]:
def inorder(root):
  if root is None:
    return
  inorder(root.left)
  print(root.elem, end=' ')
  inorder(root.right)

### *Count Nodes*

In [ ]:
def count(root):
    if root is None:
        return 0
    return 1 + count(root.left) + count(root.right)

### *InOrder (Morris)*

In [ ]:
import numpy as np
def count(root):
    if root is None:
        return 0
    return 1 + count(root.left) + count(root.right)

def inorder_morris(root):
  cur = root
  i = 0
  L = count(root)
  arr = np.array([0]*L)

  while cur is not None:
    if cur.left is None:
      # arr[i] = cur.elem
      # if i+1 == L:
      #   return arr
      # i += 1
      cur = cur.right
    else:
      pred = cur.left
      while pred.right is not None and pred.right != cur:
        pred = pred.right

      if pred.right is None:
        pred.right = cur
        cur = cur.left
      else:
        pred.right = None
        # arr[i] = cur.elem
        # if i+1 == L:
        #   return arr
        # i += 1
        cur = cur.right
  return arr

### *Reverse InOrder (Morris)*

In [ ]:
def reverse(root):
  cur = root
  while cur is not None:
    if cur.right is None:
      print(cur.elem)
      cur = cur.left
    else:
      post = cur.right
      while post.left is not None and post.left != cur:
        post = post.left
      if post.left is None:
        post.left = cur
        cur = cur.right
      else:
        print(cur.elem)
        post.left = None
        cur = cur.left
  print()

### *Insert Node*

In [ ]:
def insert(root, elem):
  cur = root
  nod = BTNode(elem)
  while cur is not None:
    if elem == cur.elem:
      print("Duplicate")
      break
    if elem < cur.elem:
      if cur.left is None:
        cur.left = nod
        break
      cur = cur.left
    if elem > cur.elem:
      if  cur.right is None:
        cur.right = nod
        break
      cur = cur.right

### *Inorder Predecessor*

In [ ]:
def inorder_predecessor(root, x):
  if x is None or root is None:
    return
  cur = root
  prev = None
  found = False
  while cur is not None:
    if x.elem < cur.elem:
      cur = cur.left
    if x.elem > cur.elem:
      prev = cur
      cur = cur.right
    elif x.elem == cur.elem:
      found = True
      break
  if not found:
    return ('Invalid')
  return prev

### *Inorder Successor*

In [ ]:
def inorder_successor(root, x):
  if x is None or root is None:
    return
  cur = root
  next = None
  found = False
  while cur is not None:
    if x.elem < cur.elem:
      cur = cur.left
    elif x > cur.elem:
      cur = cur.right
    if x.elem == cur.elem:
      found = True
      if cur.right is not None:
        next = cur.right
      break
  if not found:
    return ('Invalid')
  return next

### *Delete Node (Successor)*

In [ ]:
def minNode(root):
  cur = root
  while cur.left is not None:
    cur = cur.left
  return cur

def deleteBySuccessor(root, elem):
  if root is None:
    return
  if elem > root.elem:
    root.right = deleteBySuccessor(root.right, elem)
  elif elem < root.elem:
    root.left = deleteBySuccessor(root.left, elem)
  elif root.elem == elem:
    if root.left is None:
      return root.right
    elif root.right is None:
      return root.left
    else:
      post = minNode(root.right)
      root.elem = post.elem
      root.right = deleteBySuccessor(root.left, post.elem)
  return root

### *Delete Node (Predecessor)*

In [ ]:
def maxNode(root):
  cur = root
  while cur.right is not None:
    cur = cur.right
  return cur

def deleteByPredecessor(root, elem):
  if root is None:
    return
  if elem > root.elem:
    root.right = deleteByPredecessor(root.right, elem)
  elif elem < root.elem:
    root.left = deleteByPredecessor(root.left, elem)
  elif elem == root.elem:
    if root.left is None:
      return root.right
    elif root.right is None:
      return root.left
    else:
      pred = maxNode(root.left)
      root.elem = pred.elem
      root.left = deleteByPredecessor(root.left, pred.elem)
  return root

### *Search*

In [ ]:
def searchBST(root, elem, i = 0):
  if root is None:
    return
  if root.elem > elem:
    i = searchBST(root.left, elem, i+1)
  if root.elem < elem:
    i = searchBST(root.right, elem, i+1)
  return i

### *Balancing BST*

In [ ]:
def storeInorder(root, arr):
  if root is None:
    return
  storeInorder(root.left, arr)
  arr += [root.elem]
  storeInorder(root.right, arr)

def ArrToBST(arr, start, end):
  if start > end or (start + end)//2 >= len(arr):
    return
  mid = (start + end)//2
  root = BTNode(arr[mid])
  root.left = ArrToBST(arr, start, mid - 1)
  root.right = ArrToBST(arr, mid + 1, end)
  return root

def balanceBST(root):
  if root is None:
    return
  new_arr = []
  storeInorder(root, new_arr)
  return ArrToBST(new_arr, 0, len(new_arr))

root = BTNode(40)
n50 = BTNode(50)
# n60 = BTNode(60)
n70 = BTNode(70)
n90 = BTNode(90)
n95 = BTNode(95)
n99 = BTNode(99)

root.right = n50
n50.right = n70
# n60.right = n70
n70.right = n90
n90.right = n95
n95.right = n99

root1 = balanceBST(root)
inorder(root1)

40 50 70 90 95 99 

### *Sum of k-th Smallest*

In [ ]:
import numpy as np
def k_sum(root, k):
  cur = root
  i = 0
  result = 0

  while cur is not None:
    if cur.left is None:
      i += 1
      result += cur.elem
      if i == k:
        return result
      cur = cur.right

    else:
      pred = cur.left
      while pred.right is not None and pred.right != cur:
        pred = pred.right
      if pred.right is None:
        pred.right = cur
        cur = cur.left
      else:
        pred.right = None
        i += 1
        result += cur.elem
        if i == k:
          return result
        cur = cur.right
  return result

### *k-th Largest in BST*

In [ ]:
def k_largest(root, k):
  i = 0
  cur = root
  while cur is not None:
    if cur.right is None:
      i += 1
      if i == k:
        return cur.elem
      cur = cur.left
    else:
      post = cur.right
      while post.left is not None and post.left != cur:
        post = post.left
      if post.left is None:
        post.left = cur
        cur = cur.right
      else:
        i += 1
        if i == k:
          return cur.elem
        post.left = None
        cur = cur.left

### *Print BST Keys in given range*

In [ ]:
def print_in_range(root, x, y):
  cur = root
  while cur is not None:
    if cur.left is None:
      if x <= cur.elem <= y:
        print(cur.elem)
      cur = cur.right
    else:
      pred = cur.left
      while pred.right is not None and pred.right != cur:
        pred = pred.right
      if pred.right is None:
        pred.right = cur
        cur = cur.left
      else:
        if x <= cur.elem <= y:
          print(cur.elem)
        cur = cur.right

### *Add all greater values to every node in a given BST*

In [ ]:
def add_greater(root, Sum = np.array([0])):
  if root is None:
    return
  add_greater(root.right)
  Sum[0] += root.elem
  root.elem = Sum[0]
  add_greater(root.left)

In [ ]:
def add_greater(root):
  sum = 0
  cur = root
  while cur is not None:
    if cur.right is None:
      sum += cur.elem
      cur.elem = sum
      cur = cur.left
    else:
      post = cur.right
      while post.left is not None and post.left != cur:
        post = post.left
      if post.left is None:
        post.left = cur
        cur = cur.right
      else:
        sum += cur.elem
        cur.elem = sum
        post.left = None
        cur = cur.left

### *BST to MinHeap*

In [ ]:
def count(root):
  if root is None:
    return 0
  return 1 + count(root.left) + count(root.right)

def inorder(root, arr, i = 0):
  if root is None:
    return i
  i = inorder(root.left, arr, i)
  arr[i] = root.elem
  i += 1
  i = inorder(root.right, arr, i)
  return i

def fill_preorder(root, inorder_arr, i=0):
  if root is None:
    return i
  root.elem = inorder_arr[i]
  i+=1
  i = fill_preorder(root.left, inorder_arr, i)
  i = fill_preorder(root.right, inorder_arr, i)
  return i

def BSTtoMinHeap(root):
  arr = np.array([0]*count(root))
  inorder(root, arr)
  fill_preorder(root, arr)
  print(arr)

### *BST from Level Order*

In [ ]:
class BTNode:
  def __init__(self, elem):
    self.elem = elem
    self.left = None
    self.right = None
def getNode(data):

    # Allocate memory
    newNode = BTNode(data)

    # put in the data
    newNode.data = data
    newNode.left = None
    newNode.right = None
    return newNode

def level_order_arr(root, elem):
  if root is None:
    root = getNode(elem)
    return root
  if root.elem >= elem:
    root.left = level_order_arr(root.left, elem)
  else:
    root.right = level_order_arr(root.right, elem)
  return root

def constructBST(arr, n):
  if n == 0:
    return None
  root = None
  for i in range(0, n):
    level_order_arr(root, arr[i])
  return root

### *Driver Code*

In [ ]:
# Driver Code
n5 = BTNode(5)
n15 = BTNode(15)
n25 = BTNode(25)
n21 = BTNode(21)
n40 = BTNode(40)

n10 = BTNode(10)
n10.left = n5
n10.right = n15

n30 = BTNode(30)
n30.left = n25
n30.right = n40

# n25.left = n21

root = BTNode(20)
root.left = n10
root.right = n30

    #         20
    #        /  \
    #      10    30
    #     /  \   /  \
    #    5   15 25  40

print(f"Inorder: {inorder_morris(root)}")
print()

# #Search
# print(searchBST(root, 20))
# print(f"Inorder:", end = ' ')
# inorder(root)
# print()

# # Delete
# deleteByPredecessor(root, 40)
# inorder(root)
# print()

# print(inorder_predecessor(root, n30).elem)
# insert(root, 11)
# print()
# inorder(root)

# # Sum of k-th Smallest
# k_sum(root, 3)

# # k - th Largest
# k_largest(root, 2)

# # Printing keys in given range
# print_in_range(root, 1, 16)

# # Add greater numbers
# add_greater(root)
# inorder(root)

# # BST to MinHeap
# BSTtoMinHeap(root)
# pre_order(root)

# BST from Level Order
arr = [7, 4, 12, 3, 6, 8, 1, 5, 10]
n = len(arr)
root = constructBST(arr, n)
print(inorder_morris(root))

Inorder: [ 5 10 15 20 25 30 40]

[]


# **Heap**

## MinHeap

### *Heap Class*

In [ ]:
import numpy as np
class MinHeap:
  def __init__(self, capacity):
    self.__heap = np.array([None]*capacity)
    self.__size = 0
    self.__capacity = capacity

  def __getHeap(self):
    return self.__heap

  def swim(self):
    i = self.__size - 1
    while self.__heap[(i-1)//2] < self.__heap[i]:
      self.__heap[(i-1)//2], self.__heap[i] = self.__heap[i], self.__heap[(i-1)//2]
      i = (i-1)//2

  def sink(self, i=0):
    smallest = i
    p = ((i-1)//2)
    l = 2*i + 1
    r = 2*i + 2
    if l < len(self.__heap) and self.__heap[l] < self.__heap(smallest):
      smallest = l
    if r < len(self.__heap) and self.__heap[r] < self.__heap(smallest):
      smallest = r
    if i != smallest:
      self.__heap[smallest], self.__heap[i] = self.__heap[i], self.__heap[smallest]
      self.sink(i+1)

  def insert(self, elem):
    self.__heap[self.__size] = elem
    self.swim(self.__size)
    self.__size += 1

  def extractMin(self):
    if self.__size == 0:
      return None
    val = self.__heap[0]
    self.__size -= 1
    if self.__size == 1:
      self.__heap[0] = None
      return val
    self.__heap[0] = self.__heap[self.__size]
    self.__heap[self.__size] = None
    self.sink()
    return val

  def heapSort(self, arr):
    n = self.__size
    start = n // 2 - 1
    for i in range(start, -1, -1):
      self.sink(i)
    for i in range(n-1, 0, -1):
      self.__arr[0], self.__arr[i] = self.__arr[i], self.__arr[0]
      self.__size -= 1
      self.sink()
    self.__size = n
    return self.__arr[:self.__size]


## MaxHeap

In [ ]:
import numpy as np
class MaxHeap:
  def __init__(self, capacity):
    self.__heap = np.array([None]*capacity)
    self.__size = 0
    self.__capacity = capacity

  def __getHeap(self):
    return self.__heap

  def swim(self):
    i = self.__size - 1
    while self.__heap[(i-1)//2] < self.__heap[i]:
      self.__heap[(i-1)//2], self.__heap[i] = self.__heap[i], self.__heap[(i-1)//2]
      i = (i-1)//2

  def sink(self, i=0):
    largest = i
    p = ((i-1)//2)
    l = 2*i + 1
    r = 2*i + 2
    if l < len(self.__heap) and self.__heap[l] > self.__heap(largest):
      largest = l
    if r < len(self.__heap) and self.__heap[r] > self.__heap(largest):
      largest = r
    if i != largest:
      self.__heap[largest], self.__heap[i] = self.__heap[i], self.__heap[largest]
      self.sink(i+1)

  def insert(self, elem):
    self.__heap[self.__size] = elem
    self.swim(self.__size)
    self.__size += 1

  def extractMax(self):
    if self.__size == 0:
      return None
    val = self.__heap[0]
    self.__size -= 1
    if self.__size == 1:
      self.__heap[0] = None
      return val
    self.__heap[0] = self.__heap[self.__size]
    self.__heap[self.__size] = None
    self.sink()
    return val

  def heapSort(self, arr=None):
    n = self.__size
    start = n // 2 - 1
    for i in range(start, -1, -1):
      self.sink(i)
    for i in range(n-1, 0, -1):
      self.__heap[0], self.__heap[i] = self.__heap[i], self.__heap[0]
      self.__size -= 1
      self.sink()
    self.__size = n
    return self.__heap[:self.__size]